version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mgspy
      - POSTGRES_USER=mgspyuser
      - POSTGRES_PASSWORD=mgspypass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./dbdump.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - DB_NAME=mgspy
      - DB_USER=mgspyuser
      - DB_PASS=mgspypass
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE_URL=postgresql://mgspyuser:mgspypass@db:5432/mgspy
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - DB_NAME=mgspy
      - DB_USER=mgspyuser
      - DB_PASS=mgspypass
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE_URL=postgresql://mgspyuser:mgspypass@db:5432/mgspy
    ports:
      - "8080:8080"
    depends_on:
      - db
      - backend
    restart: unless-stopped

volumes:
  db_data: